// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kptxngsdfpmdejprefjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwdHhuZ3NkZnBtZGVqcHJlZmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDEzODUsImV4cCI6MjA3MDIxNzM4NX0.bzqOs-WEWtAE2FRAmNETQnE8L3uLW1VNDmmqUQIMYXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);